spring.application.name=BANANAPI

## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bananapi_db
spring.datasource.username=postgres
spring.datasource.password=italia032

# create and drop table, good for testing, production set to none or comment it
spring.jpa.hibernate.ddl-auto=update
